name: Build and Deploy on s3

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: npm run
        run: npx update-browserslist-db@latest

      - name: Install Dependencies
        run: npm install

      - run: npm ci  

      - name: Build
        run: npm run build  # Adjust this based on your project setup

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Upload Image to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'

        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'US East (Ohio) us-east-2'  # Change this to your AWS region
